### ISSUE TITLE
Building from scratch

### ISSUE THREAD

**Issue by panther03** [aglab2/hacktice#16]
I'm attempting to build from source right now. I see in the makefile include and lib variables there is a local folder called sm64-api referenced. I assume this is just something on your hard drive, does it exist anywhere else though?
And the symbols.ld referenced in the linker script (which is presumably in this sm64-api folder), is that from the decomp or something else?

Thanks.

**Comment by aglab2** [comment]
I made several improvements to build process to use publically available sm64-api. I have also documented the steps to build 'Hacktice.exe' from scratch.

You are more than welcome to try it out. I only tested it on Windows but I assume it is similar on other platforms too if you were to use clang.

**Comment by panther03** [comment]
Thanks! I really appreciate that. Got it to work now thanks to that.
