### ISSUE TITLE
Level data resets when changing areas

### ISSUE THREAD

**Issue by sennaif** [aglab2/hacktice#20]
Objects like red coins, secrets, and enemies reset when switching areas within an area (e.g.  entering and exiting the igloo in snowman's land).
Edit: realized this was an issue with level reset codes in general.

**Comment by aglab2** [comment]
It is possible to workaround this issue in hacktice as it is more complicated than just a batch of codes.. Let's keep the ticket opened.

**Comment by aglab2** [comment]
Resolved in 1.3.5
