### ISSUE TITLE
Death Action not triggering when hitting a death plane

### ISSUE THREAD

**Issue by aussieadam** [aglab2/hacktice#5]
The Death Action option doesn't work properly if you fall out of bounds or hit a death plane, will just take you out of the level like normal instead of triggering any of the options.

**Comment by aglab2** [comment]
Need to setup a hook for the death plane somewhere near `check_death_barrier`, need research to find the safest way to do it.

**Comment by aglab2** [comment]
Fixed in 1.3.4.1
